### ISSUE TITLE
tweet urls

### ISSUE THREAD

**Issue by PR0r** [horgh/twitter-tcl#15]
I have noticed that some tweets that are displayed are have most of the url missing?

eg. +Twitter> johnkobani99: RT @Truth2Pwer: @AngelaLoRosso @bebird where I think possibilities could lead. Area between Efrin and Kobane will be a 4 way struggle http:… 
* This looks to have the URL cut off

+Twitter> IRCUndernetOrg: RT @herszenhorn: Shortly after start of Minsk ceasefire, at midnight in east #Ukraine, initial reports are of quiet in #Debaltseve, #Donets…
* This looks to be missing the end of the tweet?

Is the bot limiting the length of each message it displays and can this be increased or removed?
Looks like this could be related to Issue #8 Was there any progress with this?

Thanks

**Comment by horgh** [comment]
It does sound like the same case case #8.

The bot won't limit the text. It's displaying the text as given.

I believe it is due to it being a retweet and the original tweet being truncated as we receive it. Those two examples are 139 characters long it appears.

It may be that the original tweet is available in the payload from the API and we could choose to display that to get the full untruncated original tweet. I'll take a look.

**Comment by PR0r** [comment]
Thanks, looking forward to hearing from you =)

**Comment by horgh** [comment]
I've come up with a way to do this.

By taking the original tweet's text and prepending the 'RT screenname:' to it we get the original tweet without truncation.

See dc7775e734662d85862aa513c70acb349cc5953d. (The twitlib.tcl part is what you would need).

**Comment by horgh** [comment]
Oh I see you edited your other comment on the commit to say it's working now.

It's possible that a full .restart was needed, if you just did a .rehash?
