### ISSUE TITLE
extended tweet mode

### ISSUE THREAD

**Issue by parkerbryan** [horgh/twitter-tcl#23]
I noticed that during retweets, they are truncated, and you even have some code in there to detect it when 'retweeted_status' is in the JSON response and prepend 'RT @name:' to the tweet output. Twitter added the ability to provide 'tweet_mode=extended' in the GET request, which gives a full_text value instead of the usual text value containing the tweet itself, but I'm running into some weirdness that I don't fully understand and hope maybe you can help. I'm more of a sysadmin than a programmer and don't do any coding, but if I stare at some code and look at the logic long enough I can start to get an idea of what's going on, but this eludes me.

Despite adding 'tweet_mode=extended' to the GET request and changing text to full_text in various areas of twitlib.tcl and twitter.tcl, I seem to still be getting a shorter version of the actual tweet, at least while I've been testing using !twit_updates until a new retweet comes along from someone I'm following.

I'm using the following recent retweet as a baseline for my testing: https://twitter.com/ThoughtsOnCyber/status/911697583525023746

I used Twitter's API console to get the extended and nonextended responses, which I've pastebinned below:
nonextended: https://pastebin.com/cxF0K92P
extended: https://pastebin.com/61uDdetZ

What's weird is that in both responses there are two text values and two full_text values. The first text value in the nonextended response is shorter than the actual retweet, despite having a truncated value of false. The second text value in the nonextended response is truncated as expected with the addition of the unicode ellipses.

For the extended response, the first full_text value is the same shortened value provided by the nonextended response, however the second full_text value in the extended response is the expected entirety of the retweet without any truncation, however I am supplied still with the first shortened value by your script, and I don't understand why. What am I missing?

I've pastebinned the files as I've modified them as well (I made a few other personal tweaks like changing the trigger and formatting of output_update to give the tweet URL):
twitlib.tcl: https://pastebin.com/ZPEnhfQw
twitter.tcl: https://pastebin.com/K0wWfSXT

It is worth noting that before I made any changes to get the extended response, the automatic announcement of the tweet (::twitlib::get_unseen_updates) gave me the actual truncated version with ellipses, while doing !twit_updates gave me the first shorter text value (the one with truncated:false in the nonextended response).

**Comment by horgh** [comment]
From looking at the extended JSON, it looks like the reason there are two `full_text` fields is that one is the retweet itself and the other is the original tweet. In this case you'd want the original tweet, so you will want to always access `retweeted_status`'s `full_text` when it is present, and otherwise use the top level `full_text`.

It sounds like the logic around `retweeted_status` in the original script could use some work. That may be part of the problem.

Changing the script to always make the extended request seems reasonable. I'd be happy to include as the new default.

I'll see if I can figure out what the problem is.

**Comment by parkerbryan** [comment]
I would be much obliged, thank you!

**Comment by horgh** [comment]
I've looked at your changes. They look good. Nice job! And thanks for bringing this up, I think it will be nice to use extended tweets.

Regarding your updates:

I think what is causing a problem is that there were missing calls to `::twitlib::fix_status`. In particular, `!twit_updates` was not using it, so the second `full_text` was never used in that case (but in other cases it was). Confusing! That would explain the discrepancy you saw.

Other than that, your changes look exactly like what needs to be done. I've incorporated nearly the same changes in the commits I just pushed, and added the missing `fix_status` calls.

If you add a `set result [::twitlib::fix_statuses $result]` to line 354 in your `twitter.tcl`, I think this will fix the problem.

I also added a new trigger so that we can retrieve a tweet by its ID so it is easier to test with a particular tweet: `!twit_get_tweet` by default. (Maybe we need to figure out a way to customize the `!` to be `.`, I like `.` these days too!)

**Comment by parkerbryan** [comment]
Aha! Very cool, makes sense now and I can confirm calling fix_statuses in that spot does the trick, totally missed that. Good call on the trigger for retrieving tweets by ID as well, I'll wedge those changes in, very handy to have. Thank you for your help and for this script, I really appreciate it.
