### ISSUE TITLE
 Update retrieval (home) failed

### ISSUE THREAD

**Issue by sacredland** [horgh/twitter-tcl#24]
[20:47:00] Update retrieval (home) failed: OAuth failure: (code: 429) {"errors":[{"message":"Rate limit exceeded","code":88}]}

**Comment by horgh** [comment]
Twitter has a fairly strict [rate limiting policy](https://developer.twitter.com/en/docs/basics/rate-limiting). For that particular call, [it falls into the 15 per 15 minutes](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-home_timeline.html) per auth token bucket.

Is this the only script/program you're using with the configured access tokens? If multiple are sharing them, you'll use up the limit more quickly of course.

Do you have it configured to only poll the home timeline? The options `poll_home_timeline` and `poll_mentions_timeline` near the top of the script control the two polling options. If you have `poll_mentions_timeline` set to 1, you could turn that off.

Another thing to consider changing is the `update_time` option so that you can stay within the limits.

Unfortunately there's not much to do other than try to back off how many calls you make.
