### ISSUE TITLE
Tcl error [::twitter::status]: Incorrect number of arguments, must be an even number.

### ISSUE THREAD

**Issue by geeknik** [horgh/twitter-tcl#31]
After upgrading from Debian 9 to Debian 11, I suppose Tcl was updated and now our eggdrop is no longer able to fetch tweets. The log file gives us this:
```
[13:44:15] Update retrieval (home) failed: Incorrect number of arguments, must be an even number.
[13:49:53] Last message repeated 5 time(s).
[13:49:53] Tcl error [::twitter::status]: Incorrect number of arguments, must be an even number.
```
I understand if you don't have time for a patch but if you could point me in the right direction, I can probably write one. Thank you. 👍🏻

**Comment by horgh** [comment]
Sorry I hadn't had time to look at this. I just tried this on a Debian 11 container and it is working okay for me. Did you have any luck resolving it?

One thing you could do is add some logging to try to figure out which line is hitting the error. You can add lines like `putlog "reached line XXX"` in various spots. It looks like `::twitter::status` is failing so that would be a good one to debug with.

**Comment by horgh** [comment]
That logging will show in the bot's partyline I believe by the way.
